[project]
name = "gestor-inventario"
version = "0.1.0"
description = "Ejercicio Prueba nivel Máster IA"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.4.0",
    "ruff>=0.11.13",
]
